import "./globals.css";
import QueryProvider from "./QueryProvider";
import { ModalProvider } from "@/context/ModalManager";
import { LabelPopupProvider } from "@/context/LabelPopupManager";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          <ModalProvider>
            <LabelPopupProvider>{children}</LabelPopupProvider>
          </ModalProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
